/* auto-generated by NAPI-RS */
/* eslint-disable */

/**
 * Which binding artifact the generated loader actually loaded: `'native'` for
 * a native addon, otherwise the `platformArchABI` of the WASI flavor. Every
 * flavor napi-rs can build is listed, because `NAPI_RS_NATIVE_LIBRARY_PATH`
 * can point the loader at a WASI artifact this package does not build itself.
 */
export declare const __napiBindingTarget: 'native' | 'wasm32-wasi' | 'wasm32-wasip1'

/** An open velo repository. */
export declare class Repo {
  static init(path: string): Promise<Repo>
  static open(path: string): Promise<Repo>
  /** Save a whole tree as a snapshot and resolve to its id. */
  saveTree(input: SaveTreeInput): Promise<string>
  treeAt(id: string): Promise<Array<TreeFile>>
  readFileAt(id: string, path: string): Promise<Buffer>
  readObject(object: string): Promise<Buffer>
  snapshot(id: string): Promise<SnapshotInfo>
  snapshotMeta(id: string): Promise<Record<string, Record<string, string>>>
  /** Resolve a snapshot name (id, prefix, branch, tag, ...) to a full id. */
  resolve(spec: string): Promise<string>
  branchTip(branch: string): Promise<string | null>
  headToken(): Promise<bigint>
}

/** Who made a snapshot. */
export interface AuthorInput {
  name: string
  email?: string
}

/** One file of a tree to save. Exactly one of `data` and `object` is given. */
export interface EntryInput {
  path: string
  /** Bytes to store. */
  data?: Buffer | string
  /** An object already in the store, to carry forward without its bytes. */
  object?: string
  /** `'regular'` (default), `'executable'` or `'symlink'`. */
  kind?: string
}

export interface SaveTreeInput {
  branch: string
  message: string
  entries: Array<EntryInput>
  parent?: string
  mergeParent?: string
  meta?: Record<string, Record<string, string>>
  author?: AuthorInput
  timestampMs?: number
  /** `[from, to]` pairs of paths this snapshot moved. */
  renames?: Array<Array<string>>
}

/** A snapshot's header. */
export interface SnapshotInfo {
  id: string
  message: string
  createdAtMs: number
  createdAt: Date
  branch: string
  parent: string | null
  mergeParent: string | null
  tag: string | null
}

/** A file as recorded in a saved tree. */
export interface TreeFile {
  path: string
  object: string
  /** `'regular'`, `'executable'` or `'symlink'`. */
  kind: string
}
